VendasLanches/Areas/Admin/Controllers/AdminOrdersController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ReflectionIT.Mvc.Paging;
using VendasLanches.Context;
using VendasLanches.Models;
using VendasLanches.ViewModels;

namespace VendasLanches.Areas.Admin.Controllers {
    
    [Area("Admin")]
    public class AdminOrdersController : Controller {
        private readonly AppDbContext _context;

        public AdminOrdersController(AppDbContext context) {
            _context = context;
        }

        // GET: Admin/AdminOrders
        //public async Task<IActionResult> Index() {
        //    return _context.Orders != null ?
        //                View(await _context.Orders.ToListAsync()) :
        //                Problem("Entity set 'AppDbContext.Orders'  is null.");
        //}

        public async Task<IActionResult> Index(string filter, int pageindex = 1,
            string sort = "Client") {
            
            IQueryable<Order> result = _context.Orders.AsNoTracking().AsQueryable();
            
            if (!string.IsNullOrWhiteSpace(filter)) {
                result = result.Where(o => o.Client.Contains(filter));
            }
            PagingList<Order> model = await PagingList.CreateAsync(result, 5, pageindex,
                sort, "Client");
            model.RouteValue = new RouteValueDictionary { { "filter", filter } };
            
            return View(model);
        }

            // GET: Admin/AdminOrders/Details/5
            public async Task<IActionResult> Details(int? id) {
            if (id == null || _context.Orders == null) {
                return NotFound();
            }

            Order order = await _context.Orders.
                Include(o => o.OrderItems).
                ThenInclude(s => s.Snack).
                FirstOrDefaultAsync(o => o.Id == id);

            if (order == null) {
                return NotFound();
            }

            OrderSnackViewModel orderSnacks = new OrderSnackViewModel() {
                Order = order,
                OrderItems = order.OrderItems!
            };

            return View(orderSnacks);
            // return View(order);
        }

        // GET: Admin/AdminOrders/Create
        public IActionResult Create() {
            return View();
        }

        // POST: Admin/AdminOrders/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Client,Phone,EMail,TotalOrder,Items,RegDate,ShippingDate,DeliveryDate")] Order order) {

            int id = 1;
            Order ord = _context.Orders.OrderBy(s => s.Id).LastOrDefault()!;
            if (ord != null) { id = ord.Id++; }

            order!.Id = id;

            if (ModelState.IsValid) {
                _context.Add(order);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(order);
        }

        // GET: Admin/AdminOrders/Edit/5
        public async Task<IActionResult> Edit(int? id) {
            if (id == null || _context.Orders == null) {
                return NotFound();
            }

            var order = await _context.Orders.FindAsync(id);
            if (order == null) {
                return NotFound();
            }
            return View(order);
        }

        // POST: Admin/AdminOrders/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Client,Phone,EMail,TotalOrder,Items,RegDate,ShippingDate,DeliveryDate")] Order order) {
            if (id != order.Id) {
                return NotFound();
            }

            if (ModelState.IsValid) {
                try {
                    _context.Update(order);
                    await _context.SaveChangesAsync();
                } catch (DbUpdateConcurrencyException) {
                    if (!OrderExists(order.Id)) {
                        return NotFound();
                    } else {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(order);
        }

        // GET: Admin/AdminOrders/Delete/5
        public async Task<IActionResult> Delete(int? id) {
            if (id == null || _context.Orders == null) {
                return NotFound();
            }

            var order = await _context.Orders
                .FirstOrDefaultAsync(m => m.Id == id);
            if (order == null) {
                return NotFound();
            }

            return View(order);
        }

        // POST: Admin/AdminOrders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id) {
            if (_context.Orders == null) {
                return Problem("Entity set 'AppDbContext.Orders'  is null.");
            }
            var order = await _context.Orders.FindAsync(id);
            if (order != null) {
                _context.Orders.Remove(order);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool OrderExists(int id) {
            return (_context.Orders?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

VendasLanches/Areas/Admin/Views/AdminOrders/Create.cshtml
@model VendasLanches.Models.Order

@{
    ViewData["Title"] = "Novo Pedido";
}

<h1>Novo</h1>
<h4>Pedido</h4>
<hr />

<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Client" class="control-label">Cliente:</label>
                <input asp-for="Client" class="form-control" />
                <span asp-validation-for="Client" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Phone" class="control-label">Telefone:</label>
                <input asp-for="Phone" class="form-control" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EMail" class="control-label">E-Mail:</label>
                <input asp-for="EMail" class="form-control" />
                <span asp-validation-for="EMail" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TotalOrder" class="control-label">Total:</label>
                <input asp-for="TotalOrder" class="form-control" />
                <span asp-validation-for="TotalOrder" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Items" class="control-label">Itens:</label>
                <input asp-for="Items" class="form-control" />
                <span asp-validation-for="Items" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RegDate" class="control-label">Data Cad:</label>
                <input asp-for="RegDate" class="form-control" />
                <span asp-validation-for="RegDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ShippingDate" class="control-label">Data Venda:</label>
                <input asp-for="ShippingDate" class="form-control" />
                <span asp-validation-for="ShippingDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DeliveryDate" class="control-label">Data Entrega:</label>
                <input asp-for="DeliveryDate" class="form-control" />
                <span asp-validation-for="DeliveryDate" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Salvar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <br />
    <a asp-action="Index">Voltar</a>
</div>

VendasLanches/Areas/Admin/Views/AdminOrders/Delete.cshtml
@model VendasLanches.Models.Order

@{
    ViewData["Title"] = "Excluir";
}

<h1>Excluir</h1>
<h3>Deseja mesmo apagar este pedido?</h3>

<div>
    <h4>Pedido</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">Cliente:</dt>
        <dd class="col-sm-10">@Model.Client</dd>
        <dt class="col-sm-2">Telefone:</dt>
        <dd class="col-sm-10">@Model.Phone</dd>
        <dt class="col-sm-2">E-Mail:</dt>
        <dd class="col-sm-10">@Model.EMail</dd>
        <dt class="col-sm-2">Total:</dt>
        <dd class="col-sm-10">@Model.TotalOrder.ToString("N")</dd>
        <dt class="col-sm-2">Items:</dt>
        <dd class="col-sm-10">@Model.Items</dd>
        <dt class="col-sm-2">Data Cad:</dt>
        <dd class="col-sm-10">@Model.RegDate.ToString("dd/MM/yyyy")</dd>
        <dt class="col-sm-2">Data Compra:</dt>
        <dd class="col-sm-10">@Model.ShippingDate.ToString("dd/MM/yyyy")</dd>
        <dt class="col-sm-2">Entrega:</dt>
        <dd class="col-sm-10">@Model.DeliveryDate.ToString("dd/MM/yyyy")</dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Excluir" class="btn btn-danger" /> |
        <a asp-action="Index">Voltar</a>
    </form>
</div>

VendasLanches/Areas/Admin/Views/AdminOrders/Details.cshtml
@model VendasLanches.ViewModels.OrderSnackViewModel

@{
    ViewData["Title"] = "Dados";
}

<h4>Pedido</h4>

<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">Número:</dt>
        <dd class="col-sm-3">@Model.Order.Id.ToString("00000")</dd>
        <dt class="col-sm-2">Cliente:</dt>
        <dd class = "col-sm-5">@Model.Order.Client</dd>
        <dt class = "col-sm-2">Telefone:</dt>
        <dd class = "col-sm-3">@Model.Order.Phone</dd>
        <dt class = "col-sm-2">E-Mail:</dt>
        <dd class = "col-sm-5">@Model.Order.EMail</dd>
@*         <dt class = "col-sm-2">Total:</dt>
        <dd class="col-sm-3">@Model.Order.TotalOrder.ToString("N")</dd>
        <dt class = "col-sm-2">Items:</dt>
        <dd class="col-sm-5">@Model.Order.Items</dd>
 *@@*         <dt class = "col-sm-2">Data Cad:</dt>
        <dd class="col-sm-10">@Model.Order.RegDate.ToString("dd/MM/yyyy")</dd>
 *@        <dt class = "col-sm-2">Data Compra:</dt>
        <dd class="col-sm-3">@Model.Order.ShippingDate.ToString("dd/MM/yyyy")</dd>
        <dt class = "col-sm-2">Entrega:</dt>
        <dd class="col-sm-5">@Model.Order.DeliveryDate.ToString("dd/MM/yyyy")</dd>
    </dl>
    <hr />

    <h4>Itens do Pedido</h4>

    <table class="table">
        @foreach (var item in Model.Order.OrderItems!) {
            //totalOrder += (item.Snack.Price * item.Quantity);

            <tr>
                <td align="left">
                    <h6>@Html.DisplayFor(modelItem => item.Snack.Name)</h6>
                </td>
                <td align="left">
                    <img src="~/images/snacks/@item.Snack.Image" class="img-fluid"
                         height="100" width="100" />
                </td>
                <td align="right">
                    <h6>Quant: @Html.DisplayFor(modelItem => item.Quantity)</h6>
                </td>
                <td align="right">
                    <h6>@string.Format("{0:C}", item.Snack.Price)</h6>
                </td>
            </tr>
        }

        <tr>
            <td colspan="3">&nbsp;</td>
            <td align="right">
                <h5>Total do Pedido: @Model.Order.TotalOrder.ToString("C")</h5>
            </td>
        </tr>
    </table>

    <a asp-action="Index" class="btn btn-outline-info">Voltar</a>
</div>

VendasLanches/Areas/Admin/Views/AdminOrders/Edit.cshtml
@model VendasLanches.Models.Order

@{
    ViewData["Title"] = "Alterar";
}

<h1>Alterar</h1>
<h4>Pedido</h4>
<hr />

<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Client" class="control-label">Cliente:</label>
                <input asp-for="Client" class="form-control" />
                <span asp-validation-for="Client" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Phone" class="control-label">Telefone:</label>
                <input asp-for="Phone" class="form-control" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EMail" class="control-label">E-Mail:</label>
                <input asp-for="EMail" class="form-control" />
                <span asp-validation-for="EMail" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ShippingDate" class="control-label">Data Venda:</label>
                <input asp-for="ShippingDate" class="form-control" />
                <span asp-validation-for="ShippingDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DeliveryDate" class="control-label">Data Entrega:</label>
                <input asp-for="DeliveryDate" class="form-control" />
                <span asp-validation-for="DeliveryDate" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Salvar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Voltar</a>
</div>

VendasLanches/Areas/Admin/Views/AdminOrders/Index.cshtml
@model ReflectionIT.Mvc.Paging.PagingList<VendasLanches.Models.Order>

@{
    ViewData["Title"] = "Pedidos";
}

<h3>Pedidos</h3>

<form method="get" class="form-inline">
    <input name="filter" class="form-control" placeholder="filtro"
           value="@Model.RouteValue!["Filter"]" />
    <button type="submit" class="btn btn-info">
        <span class="glyphicon glyphicon-search" aria-hidden="true">
            Procurar
        </span>
    </button>
</form>

Total de Pedidos: @Model.TotalRecordCount
<div>
    <vc:pager paging-list="@Model"></vc:pager>
</div>

<table class="table">
    <thead>
        <tr>
            <th>Cliente:</th>
            <th>Telefone:</th>
            <th>E-Mail:</th>
            <th>Valor:</th>
            <th>Itens:</th>
            <th>Data Compra:</th>
            <th>Data Entrega:</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model) {
            <tr>
                <td>@item.Client</td>
                <td>@item.Phone</td>
                <td>@item.EMail</td>
                <td>@item.TotalOrder.ToString("N")</td>
                <td align="center">@item.Items</td>
                <td align="center">@item.ShippingDate.ToString("dd/MM/yyy")</td>
                <td align="center">@item.DeliveryDate.ToString("dd/MM/yyy")</td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Alterar</a> |
                    <a asp-action="Details" asp-route-id="@item.Id">Dados</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Excluir</a> |
                    @* <a asp-action="OrderSnacks" asp-route-id="@item.Id">Itens</a> *@
                </td>
            </tr>
        }
    </tbody>
</table>

VendasLanches/Areas/Admin/Views/AdminOrders/OrderNotFound.cshtml
@model int

@{ViewData["Title"] = "404 Not Found";}

<div class="alert alert-danger mt-1 mb-1">
    <h1>Erro 404 - Not Found</h1>
    <hr />
    <h2>Pedido com id = @Model não encontrado!</h2>
</div>

<a asp-action="Index" asp-controller="AdminOrders" class="btn btn-outline-success">
    <h2>Retornar aos Pedidos</h2>
</a>