VendasLanches/Areas/Admin/Controllers/AdminImagesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using VendasLanches.Models.Configurations;

namespace VendasLanches.Areas.Admin.Controllers;

[Area("Admin")]
[Authorize(Roles = "Admin")]
public class AdminImagesController : Controller {

    private readonly ImagesConfiguration _configuration;
    private readonly IWebHostEnvironment _webHostEnvironment;

    public AdminImagesController(IWebHostEnvironment webHostEnvironment,
        IOptions<ImagesConfiguration> configuration) {
        _configuration = configuration.Value;
        _webHostEnvironment = webHostEnvironment;
    }

    public IActionResult Index() {
        return View();
    }

    public async Task<IActionResult> UploadImages(List<IFormFile> files) {

        if (files == null || files.Count == 0) {
            ViewData["Error"] = "Erro! Arquivos não selecionados!";
            return View(ViewData);
        }

        if (files.Count > 10) {
            ViewData["Error"] = "Erro! Quantidade de arquivos não pode ultrapassar 10!";
            return View(ViewData);
        }

        long size = files.Sum(f => f.Length);

        List<string> filePathsName = new List<string>();

        string filePath = Path.Combine(_webHostEnvironment.WebRootPath,
            _configuration.SnacksImagesFolder);

        foreach (IFormFile file in files) {
            if (file.FileName.Contains(".jpg") || file.FileName.Contains(".png")) {

                string completeFileName = string.Concat(filePath, "\\", file.FileName);
                filePathsName.Add(completeFileName);

                using (FileStream stream = new FileStream(completeFileName, FileMode.Create)) {
                    await file.CopyToAsync(stream);
                }
            }
        }

        ViewData["Result"] = $"{files.Count} arquivos foram enviados ao servidor " +
                             $"(tamamnho total: {size} bytes";

        ViewBag.Files = filePathsName;

        return View(ViewData);
    }

    public IActionResult GetImages() {

        ImageFileManagerModel model = new ImageFileManagerModel();

        string imagesPath = Path.Combine(_webHostEnvironment.WebRootPath,
            _configuration.SnacksImagesFolder);

        DirectoryInfo dir = new DirectoryInfo(imagesPath);
        FileInfo[] files = dir.GetFiles();

        model.PathImages = _configuration.SnacksImagesFolder;

        if (files.Length == 0) {
            ViewData["Error"] = $"Nenhum arquivo encontrado na pasta {imagesPath}!";
        }

        model.Images = files;

        return View(model);
    }

    public IActionResult DeleteFile(string fileName) {

        string _imgDelete = Path.Combine(_webHostEnvironment.WebRootPath,
           _configuration.SnacksImagesFolder);

        if (System.IO.File.Exists(_imgDelete)) {
            System.IO.File.Delete(_imgDelete);
            ViewData["Excluido"] = $"Arquivos {_imgDelete} excluídos com sucesso!";
        }

        return View("Index");
    }
}

VendasLanches/Areas/Admin/Views/AdminImages/GetImages.cshtml
@model ImageFileManagerModel;

@{
    ViewBag.Title = "Arquivos";
}

@if (Model.Images != null) {

    <h4>Imagens:</h4>
    <hr />
    var path = Model.PathImages;

    <div class="row">
        @foreach(FileInfo file in Model.Images) {
            <div class="column">
                <img src="~/@path/@file.Name" title="@file.Name" 
                asp-append-version="true" width="125" height="125" />
                <div style="padding:10px;text-align:left">
                    <a href="@Url.Action("Deletefile","AdminImages",
                    new {fname = file.Name})">Excluir</a>
                </div>
            </div>
        }
    </div>
}

VendasLanches/Areas/Admin/Views/AdminImages/Index.cshtml
<table border="0" width="100%">
    <tr>
        <td>
            <form method="post" enctype="multipart/form-data"
                  asp-controller="AdminImages" asp-action="UploadImages">
        
                <img src="~/images/icons/upload.png" width="100" height="100" />
                <div class="form-group">
                    <div class="col-md-10">
                        <p><b>Selecione as imagens para envio:</b></p>
                        <input type="file" name="files" multiple
                               class="button btn-outline-primary" />
                    </div>
                </div>
            </form>
            <form method="post" enctype="multipart/form-data"
                  asp-controller="AdminImages" asp-action="UploadImages">
                <div class="form-group">
                    <div class="col-md-10">
                        <input type="submit" value="Enviar Imagens"
                               class="button btn-outline-primary" />
                    </div>
                </div>
            </form>
        </td>
        @* <td width="100"></td> *@

        <td>
            <form method="post" enctype="multipart/form-data"
                  asp-controller="AdminImages" asp-action="GetImages">

                <img src="~/images/icons/visualize.png" width="100" height="100" />

                <div class="form-group">
                    <div class="col-md-10">
                        <p><strong>Visualizar as imagens no Servidor:</strong></p>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-10">
                        <input type="submit" value="Visualizar Imagens"
                               class="button btn-outline-warning" />
                    </div>
                </div>

            </form>
        </td>
    </tr>

</table>

<div class="container">
    @if (ViewData["Deleted"] != null) {
        <li>@ViewData["Deleted"]</li>
    }
</div>

VendasLanches/Areas/Admin/Views/AdminImages/UploadImages.cshtml
@{
    ViewData["Title"] = "UploadImages";
}

<img src="~/images/icons/upload.png" width="100" height="100" />
<hr />

<div class="jumbotron jumbotron-fluid">
    
    <div class="container">

        @if (ViewData["Error"] != null){
            <img src="~/images/icons/error.png" width="100" height="100" />
            <h5>@ViewData["Error"]</h5>
        }
    </div>

    <div class="container">

        @if (ViewData["Result"] != null) {
            <h5>@ViewData["Result"]</h5>
            <hr />
            @if (ViewBag.Files != null) {
                @foreach(string file in ViewBag.Files){
                    <li>@file</li>
                }
            }
        }
    </div>
</div>