VendasLanches/Models/Cart.cs
using Microsoft.EntityFrameworkCore;
using VendasLanches.Context;

namespace VendasLanches.Models;

public class Cart {

    // DBContext Instance
    private readonly AppDbContext _context;

    public Cart(AppDbContext context) {
        _context = context;
    }

    // Attributes
    public string CartId { get; set; } = string.Empty;
    public List<CartItem> CartItems { get; set; } = null!;

    // Methods
    public static Cart GetCart(IServiceProvider service) {

        // Define a session
        ISession? session = service.GetRequiredService<IHttpContextAccessor>()?.HttpContext!.Session;

        // Obtain a service of the context
        AppDbContext context = service.GetService<AppDbContext>()!;

        // Obtain or generate CartId
        string cartId = session!.GetString("CartId") ?? Guid.NewGuid().ToString();

        // Set CartId in session
        session!.SetString("CartId", cartId);

        return new Cart(context!) { CartId = cartId };
    }

    public void AddToCart(Snack snack) {

        int id = 1; 
        CartItem cartItem = _context.CartItems.OrderBy(c => c.Id).LastOrDefault()!;
        if (cartItem != null) { id = cartItem.Id + 1; }

        cartItem = _context.CartItems.SingleOrDefault(
        s => s.SnackId == snack.Id && s.CartId == CartId)!;


        if (cartItem == null) {
            cartItem = new CartItem {
                Id = id,
                CartId = CartId,
                SnackId = snack.Id,
                SnackName = snack.Name,
                Quantity = 1,
                RegDate = DateTime.Now
            };
            _context.CartItems.Add(cartItem);
        } else {
            cartItem.Quantity++;
        }
        _context.SaveChanges();
    }

    public int RemoveFromCart(Snack snack) {

        CartItem cartItem = _context.CartItems.SingleOrDefault(
            s => s.SnackId == snack.Id && s.CartId == CartId)!;

        int quantity = 0;

        if (cartItem != null) {
            if (cartItem.Quantity > 1) {
                cartItem.Quantity--;
                quantity = cartItem.Quantity;
            } else {
                _context.CartItems.Remove(cartItem);
            }
        }
        _context.SaveChanges();
        return quantity;
    }

    public List<CartItem> GetCartItems() {

        return CartItems ?? (CartItems = _context.CartItems
            .Where(c => c.CartId == CartId)
            .Include(s => s.Snack).ToList());
    }

    public void ClearCart() {

        IQueryable<CartItem> cartItems = _context.CartItems
            .Where(c => c.CartId == CartId);
        _context.CartItems.RemoveRange(cartItems);
        _context.SaveChanges();
    }

    public double GetCartTotal() {
        double totalCart = _context.CartItems
            .Where(c => c.CartId == CartId)
            .Select(c => c.Snack.Price * c.Quantity).Sum();
        return totalCart;
    }
}

VendasLanches/ViewModels/CartViewModel.cs
using VendasLanches.Models;

namespace VendasLanches.ViewModels; 

public class CartViewModel {
    public Cart Cart { get; set; } = null!;
    public double CartTotal { get; set; }

    public CartViewModel(){}

    public CartViewModel(Cart cart, double cartTotal) {
        Cart = cart;
        CartTotal = cartTotal;
    }
}

VendasLanches/Controllers/CartController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using VendasLanches.Models;
using VendasLanches.Repositories.Interfaces;
using VendasLanches.ViewModels;

namespace VendasLanches.Controllers; 

public class CartController : Controller {

    private readonly ISnackRepository _snackRepository = null!;
    private readonly Cart _cart = null!;

    public CartController(ISnackRepository snackRepository, Cart cart) {
        _snackRepository = snackRepository;
        _cart = cart;
    }

    public IActionResult Index() {

        List<CartItem> itens = _cart.GetCartItems();
        _cart.CartItems = itens;

        CartViewModel cartVM = new CartViewModel {
            Cart = _cart,
            CartTotal = _cart.GetCartTotal(),
        };

        return View(cartVM);
    }
    
    [Authorize]
    public IActionResult AddItemToCart(int snackId) {

        Snack selectedSnack = _snackRepository.Snacks.FirstOrDefault(
            s => s.Id == snackId)!;
        if (selectedSnack != null) {
            _cart.AddToCart(selectedSnack);
        }

        return RedirectToAction("Index");
    }

    [Authorize]
    public IActionResult RemoveItemFromCart(int snackId) {

        Snack selectedSnack = _snackRepository.Snacks.FirstOrDefault(
            s => s.Id == snackId)!;
        if (selectedSnack != null) {
            _cart.RemoveFromCart(selectedSnack);
        }

        return RedirectToAction("Index");
    }
}

VendasLanches/Controllers/OrderController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using VendasLanches.Models;
using VendasLanches.Repositories.Interfaces;

namespace VendasLanches.Controllers; 

public class OrderController : Controller {

    private readonly IOrderRepository _orderRepository;
    private readonly Cart _cart;

    public OrderController(IOrderRepository orderRepository, Cart cart) {
        _orderRepository = orderRepository;
        _cart = cart;
    }

    [Authorize]
    [HttpGet]
    public IActionResult Checkout() {
        return View();
    }

    [Authorize]
    [HttpPost]
    public IActionResult Checkout(Order order) {
        
        int totalItems = 0;
        double totalAmount = 0.0;

        // Get cart items
        List<CartItem> items = _cart.GetCartItems();
        _cart.CartItems = items;

        // Check if there are items on cart
        if (_cart.CartItems.Count == 0) {
            ModelState.AddModelError("", "Seu carrinho está vazio!!!!");
        }

        // Calculate amount of the cart
        foreach(CartItem item in items) {
            totalItems += item.Quantity;
            totalAmount += (item.Snack.Price * item.Quantity);
        }

        // Populate order with cart data
        order.Items = totalItems;
        order.TotalOrder = totalAmount;

        // Validate data
        if (ModelState.IsValid) {
            
            //// Create Order
            _orderRepository.CreateOrder(order);

            // Define messages
            ViewBag.Message = "Obrigado por comprar conosco! :-)";
            ViewBag.Amount = _cart.GetCartTotal();

            // Clear the cart
            _cart.ClearCart();

            // Return View
            return View("~/Views/Order/Confirm.cshtml", order);
        //} else {
        //    return Json(new { success = false, errors = ModelState.Values.Where(i => i.Errors.Count > 0) });
        }

        // Return View
        return View(order);
    }
}

VendasLanches/Controllers/SnackController.cs
using Microsoft.AspNetCore.Mvc;
using VendasLanches.Models;
using VendasLanches.Repositories.Interfaces;
using VendasLanches.ViewModels;

namespace VendasLanches.Controllers; 

public class SnackController : Controller {

    private readonly ISnackRepository _snackRepository;

    public SnackController(ISnackRepository snackRepository) {
        _snackRepository = snackRepository;
    }

    public IActionResult List(string category) {

        IEnumerable<Snack> snacks = null!;
        string snackCategory = string.Empty;

        if (string.IsNullOrEmpty(category)) {
            snacks = _snackRepository.Snacks.OrderBy(s => s.Id);
            snackCategory = "Todos os lanches";
        } else {
            snacks = _snackRepository.Snacks.Where(s => s.Category == category)
                .OrderBy(s => s.Name);
            snackCategory = category;
        }

        ViewData["Title"] = snackCategory;
        ViewData["Date"] = DateTime.Now;

        int totalSnacks = snacks.Count();
        ViewBag.Text = "Total de Lanches:";
        ViewBag.Total = totalSnacks;

        SnackListViewModel snackLVM = new SnackListViewModel {
            Snacks = snacks,
            Category = snackCategory
        };

        return View(snackLVM);
    }

    public IActionResult Details(int snackId) {

        Snack snack = _snackRepository.Snacks.FirstOrDefault(s => s.Id == snackId)!;
        return View(snack);
    }

    public ViewResult Search(string searchString) {

        IEnumerable<Snack> snacks;
        string category = string.Empty;

        if (string.IsNullOrEmpty(searchString)) {
            snacks = _snackRepository.Snacks.OrderBy(s => s.Id);
            category = "Todos os Lanches";
        } else {
            snacks = _snackRepository.Snacks
                .Where(s => s.Name.ToLower().Contains(searchString.ToLower()));
            if (snacks.Any()) category = "Lanches"; 
            else category = "Nenhum Lanche Encontrado";
        }

        return View("~/Views/Snack/List.cshtml", new SnackListViewModel {
            Category = category,
            Snacks = snacks
        });
    }
}

VendasLanches/Views/Cart/Index.cshtml
@model CartViewModel

<div class="container">
    <div class="row">
        
@*         <div class="col-1 m-1 align-items-left">
            <img src="~/images/icons/cart-icon.jpg" />
        </div>
        <div class="col-2 m-1 align-items-left">
            <h5>Seu carrinho: </h5>
        </div>
 *@
        <div class="row col-md-5">
            <span class="d-block col-md-1">
                <img src="~/images/icons/cart-icon.jpg" />
            </span>
                <span class="d-block col-md-4">
                <h6>Seu carrinho: </h6>
            </span>
        </div>
        <p></p>

        <table class="table table-bordered table-striped">

            <thead>
                <th>Quantidade</th>
                <th>Lanche</th>
                <th class="text-right">Preço</th>
                <th class="text-right">Subtotal</th>
                <th></th>
            </thead>

            <tbody>
                @foreach (CartItem item in Model.Cart.CartItems) {
                    <tr>
                        <td class="text-center col-1">@item.Quantity</td>
                        <td class="text-left">@item.SnackName</td>
                        <td class="text-right col-1">@item.Snack.Price.ToString("c")</td>
                        <td class="text-right col-1">
                            @((item.Quantity * item.Snack.Price).ToString("c"))
                        </td>

                        <td class="text-center col-1">
                            <a asp-controller="Cart" asp-action="RemoveItemFromCart"
                               asp-route-snackId="@item.Snack.Id">
                                <img src="~/images/icons/trash-icon.png" />
                            </a>
                        </td>
                    </tr>
                }
            </tbody>

            <tfoot>
                <td colspan="3" class="text-right">Total:</td>
                <td class="text-right">
                        @Model.CartTotal.ToString("c")
                </td>
            </tfoot>

        </table>

        <div class="text-right">
            <div class="btn-group">
                <a class="btn btn-success" asp-controller="Order"
                   asp-action="Checkout">Concluir Pedido</a>
                &nbsp;&nbsp;&nbsp;
                <a class="btn btn-primary" asp-controller="Snack"
                   asp-action="List">Continuar Comprando</a>
            </div>
        </div>

    </div>
</div>